include: package:flutter_lints/flutter.yaml
rules:
    - name: s1026
      excludes: ['lib/main.dart']
    - name: unused_import
      exclude: 'dev_dependencies'
    - name: const_constructors
    - name: prefer_key
    - name: const_classes